/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package GraphicalUserInterface;

import java.awt.BorderLayout;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author MHAWAN
 */
public class BadSmellAnalyticsResultPanel extends javax.swing.JPanel {

    private DefaultPieDataset data;
    private JFreeChart chart;
    private ChartPanel chartPanel;

    /**
     * Creates new form BadSmellAnalyticsResultPanel
     */
    public BadSmellAnalyticsResultPanel() {

        initComponents();
        chartPanel = null;
        jPanel1.setVisible(true);
    }

    public void setPanelForLongMethod(int totalNumberOfMethod, int NumberOfSmell) {
        jLabel1.setText("Total Number Of Methods:");
        jLabel2.setText("" + totalNumberOfMethod);
        jLabel3.setText("Total Number Of Smells:");
        jLabel4.setText("" + NumberOfSmell);
        data = new DefaultPieDataset();
        data.setValue("Methotds Without Bad Smell", new Double(totalNumberOfMethod - NumberOfSmell));
        data.setValue("Long Method Bad Smell", new Double(NumberOfSmell));
// create a chart...
        chart = ChartFactory.createPieChart("Long Method Bad Smell Analytics", data, true, true, Locale.ENGLISH);
        chartPanel = new ChartPanel(chart);
        chartPanel.setVisible(true);
        setPanelVisible();
    }

    public void setPanelForLongParameterList(int totalNumberOfList, int NumberOfSmell) {
        jLabel1.setText("Total Number Of Parameter List (including Empty List):");
        jLabel2.setText("" + totalNumberOfList);
        jLabel3.setText("Total Number Of Smells:");
        jLabel4.setText("" + NumberOfSmell);
        // chartPanel.setVisible(false);
        data = new DefaultPieDataset();
        data.setValue("ParameterList Without Bad Smell", new Double(totalNumberOfList - NumberOfSmell));
        data.setValue("Long Parameter List Bad Smell", new Double(NumberOfSmell));
// create a chart...
        chart = ChartFactory.createPieChart("Long Parameter List Bad Smell Analytics", data, true, true, Locale.ENGLISH);
        chartPanel = new ChartPanel(chart);
        chartPanel.setVisible(true);
        setPanelVisible();
    }

    public void setPanelVisible() {
        jPanel1.removeAll();
        JPanel p = new JPanel();
        p.add(chartPanel);
        jPanel1.add(p);
        jPanel1.validate();
        // jPanel1.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(0, 286, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel3});

    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
