/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package GraphicalUserInterface;

import AnalyzedProject.DetectionFlag;
import AnalyzedProject.Project;
import bsdar.Controller.BadSmellDetectionControl;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class BadSmellMainPanel extends javax.swing.JPanel {

    private BSDARMainFrame mainFrame;

    /**
     * Creates new form BadSmellMainPanel
     */
    public BadSmellMainPanel(BSDARMainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox1.setText("Detect Long Method Bad Smells");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox12.setText("Detect Long Parameter List Bad Smells");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox13.setText("Detect Switch Case Bad Smells");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Detect Bad Smells");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox13))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox13)
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:}//GEN-LAST:event_jCheckBox12ActionPerformed
        if (jCheckBox12.isSelected()) {
            DetectionFlag.setLongParameterListFlag(true);
        } else {
            DetectionFlag.setLongParameterListFlag(false);
        }

    }
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
           /*
             * ArrayList<File> files = Project.getProjectJavaFilesPath(); for
             * (File file : files) { // System.out.println(file.getName());
             * String name = file.getAbsolutePath(); name = name.replace(".java",
             * ""); name = name.substring(name.lastIndexOf("src") + 4); name =
             * name.replace("\\", "."); int pointIndex = name.lastIndexOf(".") +
             * 1; String className = name.substring(pointIndex); String
             * packageName = name.substring(0, pointIndex - 1); //
             * System.out.println(name) Parser parser = new ParserWithComments();
             * CompilationUnit cu = parser.parse(file);
             * if(DetectionFlag.isLongMethodFlag()==true){
             * LongMethodBadSmellVisitor visitor = new
             * LongMethodBadSmellVisitor(); cu.accept(visitor); if
             * (visitor.getSmell() != null) { ArrayList<String> smells =
             * visitor.getSmells(); for (String smell : smells) {
             * BadSmells.getLongMethodBadSmells().add(packageName + "\t" +
             * className + "\t" + smell); System.out.println(packageName + "\t" +
             * className + "\t" + smell); } } } /*
             *
             *
             * LongParameterListVisitor visitor=new LongParameterListVisitor();
             * cu.accept(visitor); ArrayList<String> longParameterList=new
             * ArrayList<String>();
             * longParameterList.addAll(visitor.getLongParameterList());
             * for(String method:longParameterList)
             * System.out.println(name+"\t"+method);
             *
             *
             *
             */
            if (Project.getProjectName() != null) {
                if (DetectionFlag.isLongMethodFlag() || DetectionFlag.isLongParameterListFlag()||DetectionFlag.isSwitchStatementFlag()) {
                    new BadSmellDetectionControl().control();
                    mainFrame.getBSResultPanel().setBadSmellTabs();
                    mainFrame.getBSResultPanel().setBadSmellResultTable();
                    mainFrame.setBadSmellResultPanelVisible();
                } else {
                    JOptionPane.showMessageDialog(mainFrame, "Please! select bad smell first.", "Message Alert!", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(mainFrame, "Please! select Java Project first.", "Message Alert!", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

        private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
            // TODO add your handling code here:
            if (jCheckBox1.isSelected()) {
                DetectionFlag.setLongMethodFlag(true);
            } else {
                DetectionFlag.setLongMethodFlag(false);
            }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox13.isSelected()) {
            DetectionFlag.setSwitchStatementFlag(true);
        } else {
            DetectionFlag.setSwitchStatementFlag(false);
        }
    }//GEN-LAST:event_jCheckBox13ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    // End of variables declaration//GEN-END:variables
}
