/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package GraphicalUserInterface;

import AnalyzedProject.BadSmells;
import AnalyzedProject.DetectionFlag;
import AnalyzedProject.Metrics;
import AnalyzedProject.Project;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MHAWAN
 */
public class BSDARMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form BSDARMainFrame
     */
    public BSDARMainFrame() {
        initComponents();
        metricsMainPanel = new MetricsMainPanel(this);
        badSmellMainPanel = new BadSmellMainPanel(this);
        badSmellAnalyticsPanel = new BadSmellAnalyticsPanel(this);
        BSResultPanel = new BadSmellResultPanel();
        bsaResultPanel = new BadSmellAnalyticsResultPanel();
        metricsResultPanel = new MetricsResultPanel();
        BSDCreteriaPanel = new BadSmellDetectionCreteriaPanel();
        jPanel2.setVisible(false);
        jPanel3.add(metricsMainPanel);
        jPanel3.add(badSmellAnalyticsPanel);
        jPanel3.add(badSmellMainPanel);
        jPanel7.add(metricsResultPanel);
        jPanel7.add(bsaResultPanel);
        jPanel7.add(BSResultPanel);
        jPanel3.add(BSDCreteriaPanel);
        BSResultPanel.setVisible(true);
        metricsResultPanel.setVisible(true);
        badSmellAnalyticsPanel.setVisible(false);
        metricsMainPanel.setVisible(false);
        badSmellMainPanel.setVisible(false);
        BSDCreteriaPanel.setVisible(false);
        jPanel4.setVisible(false);
        jPanel7.setVisible(false);
        jPanel5.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Select Your Java Project:");

        jTextField1.setText("jTextField1");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton1.setText("Browse Project");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/sign_error.png"))); // NOI18N
        jLabel4.setText("You select an invalid java project. Please! select Project again.");
        jPanel5.add(jLabel4);

        jPanel6.add(jPanel5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel3.setText("Project Name goes here ......");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Selected Project :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel3))
        );

        jPanel6.add(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        getContentPane().add(jPanel7);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bad Smell");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Bad Smell Detector");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Metrics");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Metrics Calculator");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Project Analytics ");

        jMenuItem5.setText("Bad Smell Analytics");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Configurations");

        jMenuItem10.setText("Set Bad Smell Detection Creteria");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        BadSmells.setSmellsEmpty();
        Project.setProjectEmpty();
        Metrics.setProjectMetricsEmpty();
        jPanel2.setVisible(true);
        badSmellAnalyticsPanel.setVisible(false);
        jPanel7.setVisible(false);
        jPanel3.setVisible(true);
        Metrics.setProjectMetricsEmpty();
        setProjectSelectionPanelEmpty();
        jPanel3.setPreferredSize(metricsMainPanel.getPreferredSize());
        badSmellMainPanel.setVisible(false);
        getBSResultPanel().setVisible(false);
        metricsMainPanel.setVisible(true);
        BSDCreteriaPanel.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here
        jPanel2.setVisible(false);
        jPanel7.setVisible(false);
        this.BSDCreteriaPanel.setVisible(false);
        metricsMainPanel.setVisible(false);
        getBSResultPanel().setVisible(false);
        badSmellMainPanel.setVisible(false);
        badSmellAnalyticsPanel.setVisible(false);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        BadSmells.setSmellsEmpty();
        Project.setProjectEmpty();
        Metrics.setProjectMetricsEmpty();
        badSmellAnalyticsPanel.setVisible(false);
        jPanel2.setVisible(true);
        jPanel7.setVisible(false);
        jPanel3.setVisible(true);
        setProjectSelectionPanelEmpty();
        jPanel3.setPreferredSize(badSmellMainPanel.getPreferredSize());
        metricsMainPanel.setVisible(false);
        BSDCreteriaPanel.setVisible(false);
        getBSResultPanel().setVisible(false);
        badSmellMainPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setProjectSelectionPanelEmpty();
        Metrics.setProjectMetricsEmpty();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Your Java Project!");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        if (fileChooser.showOpenDialog(jButton1) == JFileChooser.APPROVE_OPTION) {
            if (this.isFileChooserSelectedProjectOk(fileChooser)) {
                jTextField1.setText(Project.getProjectPath());
                if (projectContainFiles(new File(Project.getProjectSourceFolderPath()))) {
                    jLabel3.setText(Project.getProjectName());
                } else {
                    jLabel3.setText(Project.getProjectName() + "  " + "But it does not contain any Java file.");
                }
                jPanel4.setVisible(true);
                jPanel5.setVisible(false);
                Project.setProjectJavaFilesPath(projectJavaFilesPath);
                Project.setProjectJavaPackagesPath(projectJavaPackagesPath);
                projectJavaFilesPath = new ArrayList<File>();
                projectJavaPackagesPath = new ArrayList<File>();
            } else {
                whenFileChooserNotSelectRightProject();
            }

        } else {
            whenFileChooserNotSelectRightProject();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel7.setVisible(false);
        getBSResultPanel().setVisible(false);
        setProjectSelectionPanelEmpty();
        badSmellAnalyticsPanel.setVisible(false);
        jPanel3.setPreferredSize(metricsMainPanel.getPreferredSize());
        badSmellMainPanel.setVisible(false);
        metricsMainPanel.setVisible(false);
        BSDCreteriaPanel.setVisible(true);
        BSDCreteriaPanel.setMetricsValuesToTextField();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        BadSmells.setSmellsEmpty();
        Project.setProjectEmpty();
        Metrics.setProjectMetricsEmpty();
        badSmellAnalyticsPanel.setVisible(true);
        jPanel2.setVisible(true);
        jPanel7.setVisible(false);
        jPanel3.setVisible(true);
        setProjectSelectionPanelEmpty();
        jPanel3.setPreferredSize(badSmellMainPanel.getPreferredSize());
        metricsMainPanel.setVisible(false);
        BSDCreteriaPanel.setVisible(false);
        getBSResultPanel().setVisible(false);
        badSmellMainPanel.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void whenFileChooserNotSelectRightProject() {
        jTextField1.setText("");
        //jLabel4.setText("You Not Select Any Java Project.Please Select Your Java Project Again.");
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
    }

    private boolean isFileChooserSelectedProjectOk(JFileChooser fileChooser) {
        Project.setProjectPath(fileChooser.getSelectedFile().toString());
        Project.setProjectName(fileChooser.getSelectedFile().getName());

        File file = new File(Project.getProjectPath());
        File[] files = file.listFiles();
        boolean flag = false;
        for (File f : files) {
            if (f.getName().equals("src")) {
                Project.setProjectSourceFolderPath(f.getPath().toString());
                flag = true;
                break;
            }
        }
        return flag;
    }

    private void setProjectSelectionPanelEmpty() {
        jTextField1.setText("");
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        Project.setProjectEmpty();
        BadSmells.setSmellsEmpty();
        Metrics.setProjectMetricsEmpty();
    }
    /**
     * @param args the command line arguments
     */
    //Fields
    private MetricsMainPanel metricsMainPanel;
    private BadSmellAnalyticsPanel badSmellAnalyticsPanel;
    private MetricsResultPanel metricsResultPanel;
    private BadSmellAnalyticsResultPanel bsaResultPanel;
    private BadSmellMainPanel badSmellMainPanel;
    private BadSmellDetectionCreteriaPanel BSDCreteriaPanel;
    private BadSmellResultPanel BSResultPanel;
    private ArrayList<File> projectJavaFilesPath = new ArrayList<File>();
    private ArrayList<File> projectJavaPackagesPath = new ArrayList<File>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private boolean projectContainFiles(File file) {
        projectFileFilter(file);
        if (projectJavaFilesPath.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    private void projectFileFilter(File directory) {

        File[] filePath = directory.listFiles();
        for (File f : filePath) {
            if (f.isDirectory()) {
                checkJavaPackage(f);
                projectFileFilter(f);
            } else if (f.getName().toString().endsWith(".java")) {
                projectJavaFilesPath.add(f);
            }
        }
    }

    private void checkJavaPackage(File file) {
        File[] files = file.listFiles();
        for (File f : files) {
            if (f.getName().toString().endsWith(".java")) {
                projectJavaPackagesPath.add(file);
                break;
            }
        }

    }

    /**
     * @return the BSResultPanel
     */
    public BadSmellResultPanel getBSResultPanel() {
        return BSResultPanel;
    }

    public void setBadSmellResultPanelVisible() {
        jPanel7.setPreferredSize(getBSResultPanel().getSize());
        jPanel2.setVisible(false);
        BSDCreteriaPanel.setVisible(false);
        metricsMainPanel.setVisible(false);
        badSmellMainPanel.setVisible(false);
        bsaResultPanel.setVisible(false);
        getBSResultPanel().setVisible(true);
        this.getMetricsResultPanel().setVisible(false);
        jPanel7.setVisible(true);
        jPanel3.setVisible(false);
    }

    /**
     * @return the metricsResultPanel
     */
    public MetricsResultPanel getMetricsResultPanel() {
        return metricsResultPanel;
    }

    public void setMetricsResultPanelVisible() {
        jPanel7.setPreferredSize(this.getMetricsResultPanel().getSize());
        jPanel2.setVisible(false);
        BSDCreteriaPanel.setVisible(false);
        metricsMainPanel.setVisible(false);
        badSmellMainPanel.setVisible(false);
        bsaResultPanel.setVisible(false);
        getBSResultPanel().setVisible(false);
        getMetricsResultPanel().setVisible(true);
        jPanel7.setVisible(true);
        jPanel3.setVisible(false);
    }

    /**
     * @return the bsaResultPanel
     */
    public BadSmellAnalyticsResultPanel getBsaResultPanel() {
        return bsaResultPanel;
    }

    /**
     * @param bsaResultPanel the bsaResultPanel to set
     */
    public void setBsaResultPanel(BadSmellAnalyticsResultPanel bsaResultPanel) {
        this.bsaResultPanel = bsaResultPanel;
    }

    public void setBadSmellAnalyticsResultPanel() {
        if (DetectionFlag.isLongMethodAnalyticsFlag()) {
            // JOptionPane.showMessageDialog(rootPane, Metrics.getNumberOfMethods()+"@@"+BadSmells.getLongMethodBadSmells().size());
            bsaResultPanel.setPanelForLongMethod(Metrics.getNumberOfMethods(), BadSmells.getLongMethodBadSmells().size());
            DetectionFlag.setLongMethodFlag(false);
        } else if (DetectionFlag.isLongParameterListAnalyticsFlag()) {
            bsaResultPanel.setPanelForLongParameterList(Metrics.getNumberOfMethods(), BadSmells.getLongParameterListBadSmells().size());
            DetectionFlag.setLongParameterListFlag(false);
        }
        setBadSmellAnalyticsResultPanelVisible();
    }

    private void setBadSmellAnalyticsResultPanelVisible() {
        jPanel7.setPreferredSize(bsaResultPanel.getSize());
        jPanel2.setVisible(false);
        BSDCreteriaPanel.setVisible(false);
        metricsMainPanel.setVisible(false);
        badSmellMainPanel.setVisible(false);
        getBSResultPanel().setVisible(false);
        getMetricsResultPanel().setVisible(false);
        bsaResultPanel.setVisible(true);
        jPanel7.setVisible(true);
        jPanel3.setVisible(false);
    }
}
