/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package GraphicalUserInterface;

import AnalyzedProject.DetectionFlag;
import AnalyzedProject.Project;
import bsdar.Controller.MetricsDetectionControl;
import javax.swing.JOptionPane;
import metricscalculator.NumberOfPackagesMC;

    // Variables declaration - do not modify
    // Variables declaration - do not modify
/**
 *
 * @author Administrator
 */
public class MetricsMainPanel extends javax.swing.JPanel {
   
    private BSDARMainFrame mainFrame;

    /**
     * Creates new form MetricsMainPanel
     */
    public MetricsMainPanel() {
        initComponents();
    }

      /**
     * Creates new form MetricsMainPanel
     */
    public MetricsMainPanel(BSDARMainFrame mainFrame) {
        this.mainFrame=mainFrame;
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox22 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox1.setText("Number Of Packages");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox12.setText("Number Of Classes");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox13.setText("Number Of Methods");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jCheckBox22.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox22.setText("Number Of Interfaces");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Calculate Metrics");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox14.setText("Number Of Member Classes");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox15.setText("Number Of Local Classes");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox16.setText("Number Of Top Level Classes");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });

        jCheckBox17.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox17.setText("Number Of Static Methods");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox18.setText("Number Of  Fields");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 0, 14));
        jCheckBox19.setText("Number Of Static Fields");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox14)
                            .addComponent(jCheckBox15)
                            .addComponent(jCheckBox16))
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox22)
                            .addComponent(jCheckBox13)
                            .addComponent(jCheckBox17)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox19)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox12.isSelected())
        {
            DetectionFlag.setNumberOfClassesflag(true);
        }
        else
        {
            DetectionFlag.setNumberOfClassesflag(false);
        }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      //  NumberOfPackagesMC pakageCalculator=new NumberOfPackagesMC();
        if(Project.getProjectName()!=null)
        {
            if(DetectionFlag.isNumberOfClassesflag() || DetectionFlag.isNumberOfFieldsflag() || DetectionFlag.isNumberOfInterfacesflag() || DetectionFlag.isNumberOfLocalClassesFlag() || DetectionFlag.isNumberOfMemberClassesFlag() || DetectionFlag.isNumberOfMethodFlag() || DetectionFlag.isNumberOfPackagesflag() || DetectionFlag.isNumberOfStaticFieldsFlag() || DetectionFlag.isNumberOfStaticMethodsFlag() || DetectionFlag.isNumberOfTopLevelClassesFlag())
            {
                
        MetricsDetectionControl mdc=new MetricsDetectionControl();
        mdc.control();
       
       mainFrame.getMetricsResultPanel().setMetricsResultPanel();
     mainFrame.setMetricsResultPanelVisible();
            }
            else
            {
                JOptionPane.showMessageDialog(mainFrame, "Plz! select Metrics option pane first.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(mainFrame, "Plz! select java project first.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox14.isSelected())
        {
            DetectionFlag.setNumberOfMemberClassesFlag(true);
        }
        else
        {
            DetectionFlag.setNumberOfMemberClassesFlag(false);
        }
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox15.isSelected())
        {
            DetectionFlag.setNumberOfLocalClassesFlag(true);
        }
        else
        {
            DetectionFlag.setNumberOfLocalClassesFlag(false);
        }

    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox16.isSelected())
        {
            DetectionFlag.setNumberOfTopLevelClassesFlag(true);
        }
        else
        {
            DetectionFlag.setNumberOfTopLevelClassesFlag(false);
        }

    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            DetectionFlag.setNumberOfPackagesflag(true);
        }
        else
        {
              DetectionFlag.setNumberOfPackagesflag(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox22.isSelected())
        {
            DetectionFlag.setNumberOfInterfacesflag(true);
        }
        else
        {
            DetectionFlag.setNumberOfInterfacesflag(false);
        }

    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox13.isSelected())
        {
            DetectionFlag.setNumberOfMethodFlag(true);
        }
        else
        {
            DetectionFlag.setNumberOfMethodFlag(false);
        }

    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox17.isSelected())
        {
            DetectionFlag.setNumberOfStaticMethodsFlag(true);
                    }
        else
        {
            DetectionFlag.setNumberOfStaticMethodsFlag(false);
            
        }

    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox18.isSelected())
        {
            DetectionFlag.setNumberOfFieldsflag(true);
        }
        else
        {
            DetectionFlag.setNumberOfFieldsflag(false);
        }

    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox19.isSelected())
        {
            DetectionFlag.setNumberOfStaticFieldsFlag(true);
        }
        else
        {
            DetectionFlag.setNumberOfStaticFieldsFlag(false);
        }

    }//GEN-LAST:event_jCheckBox19ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables


}
